My_Ecom_projects/App_Order/urls.py
from django.urls import path
from .views import add_to_card,view_cart,remove_from_cart,increase_card,decrese_card,complate_order

app_name='app_order'

urlpatterns=[
    path('add/<pk>/',add_to_card,name='add'),
    path('cart/',view_cart,name='cart'),
    path('remove/<int:pk>/',remove_from_cart,name='remove'),
    path('add_quentity/<pk>',increase_card,name='increase'),
    path('remove_quentity/<pk>/',decrese_card,name='decrise_quentity'),
    path('complite/',complate_order,name='ordered')
]

My_Ecom_projects/App_Shop/urls.py
from django.urls import path
from .views import Home,Detail_product


app_name='app_shop'

urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('product/<pk>',Detail_product.as_view(),name='product'),
]

My_Ecom_projects/App_payment/urls.py
from django.urls import path
from .views import checkout,payment,complitpay,perches
app_name='App_payment'

urlpatterns=[
    path('checkout/',checkout,name='checkout'),
    path('pay/',payment,name='payment'),
    path('com/',complitpay,name='complite'),
    path('parch/<val_id>/<tran_id>/',perches,name='perches')
]

My_Ecom_projects/My_Ecom_projects/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Ecom_projects/App_Order/models.py
from django.db import models
from django.conf import settings
from App_Shop.models import Product

# Create your models here.
class Card(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='cart')
    item=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='cart')
    quentity=models.IntegerField(default=1)
    purecesh=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quentity}X{self.item}'

    def get_total(self):
        total=self.item.price * self.quentity
        float_total=format(total,'0.2f')
        return float_total


class Order(models.Model):
    orderitem=models.ManyToManyField(Card)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    paymentId=models.CharField(max_length=264,null=True,blank=True)
    orderId=models.CharField(max_length=264,blank=True,null=True)

    def get_totals(self):
        total=0
        for item in self.orderitem.all():
            total += float(item.get_total())
        return total

My_Ecom_projects/App_Order/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Order,Card
from App_Shop.models import Product
from django.contrib import messages

# Create your views here.

# @login_required
def add_to_card(request,pk):
    item=get_object_or_404(Product,pk=pk)
    order_item=Card.objects.get_or_create(item=item,user=request.user,purecesh=False)

    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.orderitem.filter(item=item).exists():
            order_item[0].quentity += 1
            order_item[0].save()
            messages.info(request,'this item  was updated.....')
            return redirect('app_shop:home')
        else:
            order.orderitem.add(order_item[0])
            messages.success(request,'your item add successfully ....')
            return redirect('app_shop:home')

    else:
        order=Order(user=request.user)
        order.save()
        order.orderitem.add(order_item[0])
        messages.success(request,'order successfully created ')
        return redirect('app_shop:home')



def view_cart(request):
    carts=Card.objects.filter(user=request.user,purecesh=False)
    orders=Order.objects.filter(user=request.user,ordered=False)
    if carts.exists() and orders.exists():
        order=orders[0]
        return render(request,'App_Order/cart.html',context={'carts':carts,'orders':order})
    else:
        return redirect('app_shop:home')
#
@login_required
def remove_from_cart(request,pk):
    item=get_object_or_404(Product,pk=pk)
    order=Order.objects.filter(user=request.user,ordered=False)
    if order.exists():
        order_item=order[0]
        if order_item.orderitem.filter(item=item).exists():
            myorder=Card.objects.filter(user=request.user,item=item,purecesh=False)[0]
            myorder.delete()
            messages.success(request,'successfully delete.............')
            return redirect('app_order:cart')

        else:
            messages.info(request,'your product not in the cart')

            return redirect('app_shop:home')
    else:
        return redirect('app_shop:home')
#
def increase_card(request,pk):
    item=get_object_or_404(Product,pk=pk)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.orderitem.filter(item=item).exists():
            item_order=Card.objects.filter(user=request.user,item=item,purecesh=False)[0]
            if item_order.quentity >=1 :
                item_order.quentity += 1
                item_order.save()
                return redirect('app_order:cart')
            else:
                messages.info(request,f'{item_order.item.name} is not in the cart')
                return redirect('app_shop:home')
        else:
            return redirect('app_shop:home')
    else:
        return redirect('app_shop:home')


@login_required
def decrese_card(request,pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitem.filter(item=item).exists():
            item_order = Card.objects.filter(user=request.user, item=item, purecesh=False)[0]
            if item_order.quentity > 1:
                item_order.quentity -= 1
                item_order.save()
                return redirect('app_order:cart')
            else:
                item_order.delete()
                return redirect('app_order:cart')
        else:
            return redirect('app_shop:home')
    else:
        return redirect('app_shop:home')


def complate_order(request):
    try:
        com_order=Order.objects.filter(user=request.user,ordered=True)
        contex={'order':com_order}
    except:
        contex=None
        messages.info(request,'you havent any order ')
    return render(request,'App_Order/order.html',contex)

My_Ecom_projects/templates/App_Order/cart.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block style %} {% endblock %}
{% block body %}
<div class="container">
    {% include 'navebar.html' %}
    <div class="my-5">
        <h2>Your cart:</h2>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col" width="15%"></th>
                <th scope="col">Product Name</th>
                <th scope="col">Quentity</th>
                <th scope="col" align="right">price</th>
                <th scope="col">remove</th>
            </tr>
            </thead>
            <tbody>
            {% for cart in carts %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <th>{{ cart.item.name}}</th>
                <th>
                    <a href="{% url 'app_order:decrise_quentity' cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                    {{ cart.quentity }}
                    <a href="{% url 'app_order:increase' cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                </th>
                <th>
                    &#2547;
                    {{ cart.get_total }}
                </th>
                <th><a href="{% url 'app_order:remove' cart.item.pk %}" class="btn btn-danger">Remove</a></th>
            </tr>
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="2" align="right">Total</td>
                <td >&#2547;{{ orders.get_totals }}</td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right">
                    <a href="{% url 'app_shop:home' %}" class="btn btn-warning mr-5">Continue shot</a>
                    <a href="{% url 'App_payment:checkout' %}" class="btn btn-primary mr-5">Procied to card</a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

My_Ecom_projects/templates/App_Order/order.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block style %} {% endblock %}
{% block body %}
    {% for x in order %}
        {{ x }}<br>
    {% endfor %}
{% endblock %}