My_Ecom_projects/App_Login/urls.py
from django.urls import path
from . import views



app_name='app_login'

urlpatterns=[
    path('signup',views.sign_up,name='singup_page'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.create_Profile,name='profile'),
]

My_Ecom_projects/App_Order/urls.py
from django.urls import path
from .views import add_to_card,view_cart,remove_from_cart,increase_card,decrese_card,complate_order

app_name='app_order'

urlpatterns=[
    path('add/<pk>/',add_to_card,name='add'),
    path('cart/',view_cart,name='cart'),
    path('remove/<int:pk>/',remove_from_cart,name='remove'),
    path('add_quentity/<pk>',increase_card,name='increase'),
    path('remove_quentity/<pk>/',decrese_card,name='decrise_quentity'),
    path('complite/',complate_order,name='ordered')
]

My_Ecom_projects/App_Shop/urls.py
from django.urls import path
from .views import Home,Detail_product


app_name='app_shop'

urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('product/<pk>',Detail_product.as_view(),name='product'),
]

My_Ecom_projects/My_Ecom_projects/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Ecom_projects/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block title %}eComerceSite{% endblock %}</title>
    {% block style %}

    {% endblock %}

  </head>
  <body>

    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %}class="alert alert-{{message.tags}} alert-dismissible fade show mt-1" {% endif %}role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endfor %}
      {% endif %}
      </div>
      {% block body %}

    {% endblock %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

My_Ecom_projects/templates/example.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block style %} {% endblock %}
{% block body %}
<div class="container">
    {% include 'navebar.html' %}
    <div class="my-5">
        <h2>Your cart:</h2>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col" width="15%"></th>
                <th scope="col">Product Name</th>
                <th scope="col">Quentity</th>
                <th scope="col" align="right">price</th>
                <th scope="col">remove</th>
            </tr>
            </thead>
            <tbody>
            {% for cart in carts %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <th>{{ cart.item.name}}</th>
                <th>
                    <a href="{% url 'app_order:decrise_quentity' cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                    {{ cart.quentity }}
                    <a href="{% url 'app_order:increase' cart.item.pk %}" class="mr-2"><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                </th>
                <th>
                    &#2547;
                    {{ cart.get_total }}
                </th>
                <th><a href="{% url 'app_order:remove' cart.item.pk %}" class="btn btn-danger">Remove</a></th>
            </tr>
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="2" align="right">Total</td>
                <td >&#2547;{{ orders.get_totals }}</td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right">
                    <a href="{% url 'home' %}" class="btn btn-warning mr-5">Continue shot</a>
                    <a href="" class="btn btn-primary mr-5">Procied to card</a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

My_Ecom_projects/templates/navebar.html
{% load static %}
{% load tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'app_shop:home' %}"><img src="{% static 'img/favicon.ico' %}" alt="" width="30px" height="30px" style="border:1px solid red; border-radius:50%"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">


      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_order:cart' %}"><i class="fa fa-shopping-cart"></i>cart
        <span class="badge badge-light">{{ request.user|cart_total }}</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user-tie"></i>{{ request.user.profile.username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'app_login:profile' %}">Profile</a>
          <a class="dropdown-item" href="{% url 'app_order:ordered' %}">Order</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'app_login:logout' %}">logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_login:singup_page' %}">Signup</i>cart</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app_login:login' %}">Login</i>cart</a>
      </li>

      {% endif %}
    </ul>
  </div>
</nav>