My_Ecom_projects/App_Order/urls.py
from django.urls import path
from .views import add_to_card,view_cart,remove_from_cart,increase_card,decrese_card,complate_order

app_name='app_order'

urlpatterns=[
    path('add/<pk>/',add_to_card,name='add'),
    path('cart/',view_cart,name='cart'),
    path('remove/<int:pk>/',remove_from_cart,name='remove'),
    path('add_quentity/<pk>',increase_card,name='increase'),
    path('remove_quentity/<pk>/',decrese_card,name='decrise_quentity'),
    path('complite/',complate_order,name='ordered')
]

My_Ecom_projects/App_Shop/urls.py
from django.urls import path
from .views import Home,Detail_product


app_name='app_shop'

urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('product/<pk>',Detail_product.as_view(),name='product'),
]

My_Ecom_projects/My_Ecom_projects/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Ecom_projects/App_Shop/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title=models.CharField(max_length=254)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='Categories'

class Product(models.Model):
    mainimg=models.ImageField(upload_to='Product')
    name=models.CharField(max_length=264)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name='category')
    privies_text=models.TextField(max_length=200,verbose_name='Privies Text')
    detail_text = models.TextField(max_length=1000,verbose_name='Detail Text')
    price=models.FloatField()
    old_price=models.FloatField(default=0.00)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering=['-created','name']

My_Ecom_projects/App_Shop/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Category, Product
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'
    context_object_name = 'all_product'


class Detail_product(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = 'myproduct'
    template_name = 'App_Shop/productdetail.html'

My_Ecom_projects/templates/App_Shop/home.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block style %}
    <style>
      .mysatow{
            box-shadow: 4px 0px 4px 1px #00000061;
        }
    </style>
    {% endblock %}
{% block body %}


 <div class="container">
     {% load static %}
     {% include 'navebar.html' %}
        <div class="row">
            {% for product in all_product %}
            <div class="col-lg-3 col-md-6 col-sm-12 mt-4">
                <div class="card mysatow" style="">
                      <img src="/media/{{ product.mainimg }}" alt="some problame" width="100%" height="200px">
                      <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">
                            <span class="price-new">&#2547:{{product.price}}</span>
                        <span><del class="price-old">&#2547:{{product.old_price}}</del></span>
                        </p>
                        <a href="{% url 'app_shop:product' product.pk %}" class="btn btn-primary">Detail</a>
                      </div>
                    </div>


            </div>

            {% empty %}
                <h3>there are no product </h3>
            {% endfor %}
    </div>

 </div>

{% endblock %}

My_Ecom_projects/templates/App_Shop/productdetail.html
{% extends 'base.html' %}
{% block body %}

    <div class="container">
        {% include 'navebar.html' %}
        <div class="row">
            <div class="col-md-6">
                <img src="/media/{{ myproduct.mainimg}}" alt="" width="100%" height="450px">
            </div>
            <div class="col-md-6">

                <div class="card mt-3 " style="">
                      <div class="card-header">{{ myproduct.name }}</div>
                      <div class="card-body">
                        <h5 class="card-title">Discript</h5>
                        <p class="card-text">{{ myproduct.detail_text|linebreaks }}</p>
                          <p>&#2547 : {{myproduct.price}}</p>
                          <p>{{ myproduct.created|date:"d-M , Y"}}</p>
                          <a href="{% url 'app_order:add' myproduct.pk  %}"  class="btn btn-outline-success"><i class="fa  fa-shopping-cart mr-1"></i>add to cart</a>
                      </div>
                </div>
        </div>
    </div>
{% endblock %}