My_Ecom_projects/App_Shop/urls.py
from django.urls import path
from .views import Home,Detail_product


app_name='app_shop'

urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('product/<pk>',Detail_product.as_view(),name='product'),
]

My_Ecom_projects/App_payment/urls.py
from django.urls import path
from .views import checkout,payment,complitpay,perches
app_name='App_payment'

urlpatterns=[
    path('checkout/',checkout,name='checkout'),
    path('pay/',payment,name='payment'),
    path('com/',complitpay,name='complite'),
    path('parch/<val_id>/<tran_id>/',perches,name='perches')
]

My_Ecom_projects/My_Ecom_projects/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_payment.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Ecom_projects/App_payment/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class BillingAddress(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    address=models.CharField(max_length=264,blank=True)
    zipcode=models.CharField(max_length=20,blank=True)
    city=models.CharField(max_length=30,blank=True)
    country=models.CharField(max_length=20,blank=True)

    def __str__(self):
        return f'{self.user.profile.username} billing address'

    def is_fully_filled(self):
        print(self._meta.get_fields())
        fields_names = [f.name for f in self._meta.get_fields()]
        print('------------------model option is hare ----------------------')
        print(fields_names)

        for field_name in fields_names:
            value=getattr(self,field_name)
            if value is None or value == "":
                return False
        return True

    class Meta:
        verbose_name_plural= 'Bulling Address'

My_Ecom_projects/App_payment/forms.py
from django import forms
from .models import BillingAddress

class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['address','zipcode','city','country']

My_Ecom_projects/App_payment/views.py
from django.shortcuts import render,HttpResponse,redirect,HttpResponseRedirect
from .forms import BillingForm
from .models import BillingAddress
from App_Order.models import Order,Card
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# for payment
from sslcommerz_python.payment import SSLCSession
from decimal import Decimal
import requests
import socket


# Create your views here.
@login_required()
def checkout(request):
    save_address=BillingAddress.objects.get_or_create(user=request.user)[0]
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    order_item=order_qs[0].orderitem.all()
    total_order=order_qs[0].get_totals()

    form=BillingForm(instance=save_address)
    if request.method == 'POST':
        form=BillingForm(request.POST,instance=save_address)
        if form.is_valid():
            form.save()
            messages.success(request,'successfully registered............')

    return render(request,'App_payment/checkout.html',context={'form':form,'order_item':order_item,'total':total_order,'save_address':save_address})


@login_required()
def payment(request):
    saved_address=BillingAddress.objects.get_or_create(user=request.user)[0]
    if not saved_address.is_fully_filled():
        messages.info(request,'inter Shipping address properly')
        return redirect("App_payment:checkout")

    if not request.user.profile.is_fully_filled():
        messages.info(request,'full field to your profile ')
        return redirect('app_login:profile')
    # payment getway is started hare---------------------------------------------------------------------
    stror_id = 'asadu5f9ab871f41b5'  #mail enformation ssl send me in my email
    api_key = 'asadu5f9ab871f41b5@ssl' #mail enformation ssl send me in my email
    mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=stror_id,
                            sslc_store_pass=api_key)
    # section two and here is kddkkd---------------------------------------
    status_url=request.build_absolute_uri(reverse("App_payment:complite"))
    mypayment.set_urls(success_url=status_url, fail_url=status_url,
                       cancel_url=status_url, ipn_url=status_url)

    #section three is hare it is very impornt for product------------------
    order_qs=Order.objects.get(user=request.user,ordered=False)
    order_item=order_qs.orderitem.all()
    total_order= order_qs.get_totals()
    mypayment.set_product_integration(total_amount=Decimal(total_order), currency='BDT', product_category='oneck',
                                      product_name=order_item, num_of_item=len(order_item), shipping_method='Curiar',
                                      product_profile='None')

    #section four is hare it is very imporent for customer information ---------
    current_user=request.user
    mypayment.set_customer_info(name=current_user.profile.full_name, email=current_user.email, address1=current_user.profile.address_1,
                                address2=current_user.profile.address_1, city=current_user.profile.city, postcode=current_user.profile.zipcode, country=saved_address.country,
                                phone=current_user.profile.phone)

    # section five is hare it is very imporent for customer information ---------
    mypayment.set_shipping_info(shipping_to=current_user.profile.full_name, address=saved_address.address, city=saved_address.city, postcode=saved_address.zipcode,
                                country=saved_address.country)

    response_data = mypayment.init_payment()
    return redirect(response_data['GatewayPageURL'])


@csrf_exempt
def complitpay(request):
    if request.method == 'POST':
        send_data=request.POST
        # print(send_data)
        status=send_data['status']
        if status == 'VALID':
            rsk_title=send_data['risk_title']
            if rsk_title=='Safe':
                val_id = send_data['val_id']
                tran_id = send_data['tran_id']
                messages.success(request,'your transcktion successfully')
                return HttpResponseRedirect(reverse("App_payment:perches",kwargs={'val_id':val_id,'tran_id':tran_id}))
            if rsk_title != 'Safe':
                val_id = send_data['val_id']
                tran_id = send_data['tran_id']
                messages.info(request,'some risk from tranjecktion but dan...')
                return HttpResponseRedirect(
                    reverse("App_payment:perches", kwargs={'val_id': val_id, 'tran_id': tran_id}))

        if status == 'CANCELLED':
            val_id = send_data['val_id']
            tran_id = send_data['tran_id']
            messages.warning(request,'you have cancle your transcktion')
            return HttpResponseRedirect(reverse("App_payment:perches", kwargs={'val_id': val_id, 'tran_id': tran_id}))
        if status == 'FAILED':
            messages.warning(request,'not success transection happend')
            return render(request,'App_payment/complite.html',context={})

@login_required()
def perches(reques,val_id,tran_id):
    order=Order.objects.get(user=reques.user,ordered=False)
    order.ordered=True
    order.orderId=val_id
    order.paymentId=tran_id
    order.save()
    cart2=Card.objects.filter(user=reques.user,purecesh=False)
    for x in cart2:
        x.purecesh=True
        x.save()
    return redirect('app_shop:home')

My_Ecom_projects/templates/App_payment/checkout.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block style %} {% endblock %}
{% block body %}


<div class="container">
    {% include 'navebar.html' %}
    <h2>Bulling your address : </h2>
    <div class="row">
        {% load crispy_forms_tags %}
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success">
            </form>
        </div>
        <div class="col-md-4 mt-5">
            <div class="card">
                <div class="card-body">
                    <table class="table">
                        {% for x in order_item %}
                            <tr>
                                <td class="mx-auto" colspan="4">
                                    {{x.item.name}} X {{x.quentity}}
                                </td>
                            </tr>
                        {% endfor %}
                            <tr>
                                <td class="pt-4"> Total : {{ total }}&#2547;</td>
                                 <td>
                                     {% if save_address.is_fully_filled %}
                                        <a href="{% url 'App_payment:payment' %}" class="btn btn-sm btn-primary mt-2">make payment</a>
                                    {% else %}
                                        <p>sobgupai puron koro</p>
                                    {% endif %}
                                 </td>
                            </tr>

                    </table>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">

            </div>
        </div>
    </div>
</div>
{% endblock %}

My_Ecom_projects/templates/App_payment/complite.html
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    {% load static %}
      <meta http-equiv="refresh" content="5; url = {% url 'app_shop:home' %} ">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>payment dlkdkldsl </title>


  </head>
  <body>

    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %}class="alert alert-{{message.tags}} alert-dismissible fade show mt-1" {% endif %}role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endfor %}
      {% endif %}
      </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

My_Ecom_projects/templates/App_payment/payment.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block style %} {% endblock %}
{% block body %}
    payment is successfully done.............
{% endblock %}